### PR TITLE
Jira/nms 7191

### PR DESCRIPTION
**Pull request by mvrueden**

### CODE REVIEW

**Comment by mvrueden** [comment]
Welcome @blackpoplar.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username blackpoplar.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by mvrueden** [comment]
Welcome @blackpoplar.

We would like to thank you for your contribution.

I could not find a signed OpenNMS Contributor Agreement (OCA) assigned to the username blackpoplar.
In order to maintain some order with respect to the copyright to the code,
every contributor is asked to sign a "Contributor Agreement".

The OpenNMS Contributor Agreement can be downloaded [here](http://www.opennms.org/documentation/ContributorAgreement.pdf).
Please send a signed copy to oca@opennms.org.

If you need more information, please visit http://www.opennms.org/wiki/Contributor_Agreement

**Comment by blackpoplar** [comment]
I've definitely completed an OCA ;-). But I think we were using sourceforge at the time and the username would have been something like jsartin..... However If you would like another one, you are very welcome.

**Comment by mvrueden** [comment]
Hey Alfred, what are you doing? Can you please recheck blackpoplar's OCA?

**Pull request closed without merging**
